.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DOUBLEDOWN\-INOFITY" "1" "September 2010" "DevStructure" "Doubledown"
.
.SH "NAME"
\fBdoubledown\-inofity\fR \- sync local changes to a remote directory
.
.SH "SYNOPSIS"
\fBdoubledown\-inotify\fR \fIlocal\fR [\fIuser\fR@]\fIserver\fR:\fIremote\fR
.
.SH "DESCRIPTION"
\fBdoubledown\-inotify\fR watches \fIlocal\fR using \fBinotifywait\fR(1), relaying changes to the \fIremote\fR directory on \fIserver\fR\.
.
.P
Directories created within \fIlocal\fR are created remotely using ssh(1)\. Files and directories removed within \fIlocal\fR are removed remotely using ssh(1)\. Files that are created or changed are uploaded using rsync(1)\.
.
.P
This program requires Linux with a kernel newer than 2\.6\.13\.
.
.SH "OPTIONS"
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show a help message\.
.
.SH "THEME SONG"
The Arcade Fire \- "The Suburbs"
.
.SH "AUTHOR"
Richard Crowley \fIrichard@devstructure\.com\fR
.
.SH "SEE ALSO"
\fBdoubledown\fR was written to make it easier for DevStructure users to use Textmate and other IDEs but it\'s far from the only way to skin the cat\. See \fIhttp://docs\.devstructure\.com/working_remotely\fR for more options\.
